sdm845-common: Use oneplus-fwk from a separated repo
AshutoshSundresh:
Taken from https://github.com/MartinJesusDev/device_xiaomi_sm8250-common/commit/e185a430b09ae55d527907ce27b7d4a29436e670

error: frameworks/base/boot/Android.bp:44:1: "platform-bootclasspath" depends on undefined module "oneplus-fwk.oneplus_sdm845"
Module "platform-bootclasspath" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "oneplus-fwk.oneplus_sdm845" can be found in these namespaces: ["device/oneplus/sdm845-common"]

* platform-bootclasspath cannot depend
  on something from a non-root soong namespace